// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nickvision.Desktop.Keyring
{
    public partial class KeyringDbContextModel
    {
        private KeyringDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("1682803e-7df8-4ae1-905b-4b203d7dfe07"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var credential = CredentialEntityType.Create(this);

            CredentialEntityType.CreateAnnotations(credential);

            AddAnnotation("ProductVersion", "10.0.5");
        }
    }
}
