// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Nickvision.Desktop.Keyring;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(KeyringDbContext), typeof(KeyringDbContextModel))]
