// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nickvision.Desktop.Keyring
{
    [DbContext(typeof(KeyringDbContext))]
    public partial class KeyringDbContextModel : RuntimeModel
    {
        private static readonly bool _useOldBehavior31751 =
            global::System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

        static KeyringDbContextModel()
        {
            var model = new KeyringDbContextModel();

            if (_useOldBehavior31751)
            {
                model.Initialize();
            }
            else
            {
                var thread = new global::System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
                thread.Start();
                thread.Join();

                void RunInitialization()
                {
                    model.Initialize();
                }
            }

            model.Customize();
            _instance = (KeyringDbContextModel)model.FinalizeModel();
        }

        private static KeyringDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
